"""add image content type

Revision ID: 3c5952f9329f
Revises: bf48f173f4c7
Create Date: 2026-08-17 20:36:12.082319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c5952f9329f'
down_revision: Union[str, Sequence[str], None] = 'bf48f173f4c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('food_images', sa.Column('content_type', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('food_images', 'content_type')
    # ### end Alembic commands ###
