"""create food images table

Revision ID: bf48f173f4c7
Revises: f6a9cf197a37
Create Date: 2026-08-17 19:14:41.482048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf48f173f4c7'
down_revision: Union[str, Sequence[str], None] = 'f6a9cf197a37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('food_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('storage_key', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_food_images_id'), 'food_images', ['id'], unique=False)
    op.create_index(op.f('ix_food_images_user_id'), 'food_images', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_food_images_user_id'), table_name='food_images')
    op.drop_index(op.f('ix_food_images_id'), table_name='food_images')
    op.drop_table('food_images')
    # ### end Alembic commands ###
