"""add user ownership to pantry items

Revision ID: f6a9cf197a37
Revises: ddbf0c5d481a
Create Date: 2026-08-17 18:26:59.990959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6a9cf197a37'
down_revision: Union[str, Sequence[str], None] = 'ddbf0c5d481a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pantry_items', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_pantry_items_user_id'), 'pantry_items', ['user_id'], unique=False)
    op.create_foreign_key(None, 'pantry_items', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pantry_items', type_='foreignkey')
    op.drop_index(op.f('ix_pantry_items_user_id'), table_name='pantry_items')
    op.drop_column('pantry_items', 'user_id')
    # ### end Alembic commands ###
